import os
from pathlib import Path

import numpy as np
import open3d as o3d
from graspnetAPI import GraspGroup


# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------

INPUT_ROOT = Path("./outputs/sinobj")
OUTPUT_ROOT = Path("./grasppcdviz/sinobj")


# ---------------------------------------------------------
# Visualization parameters
# ---------------------------------------------------------

POINTS_PER_GRASP = 500

CONTACT_SPHERE_POINTS = 80

# meters
CONTACT_SPHERE_RADIUS = 0.008

# 0 = all grasps
MAX_GRASPS = 0


# ---------------------------------------------------------
# Load ZeroGrasp .pts
# ---------------------------------------------------------

def load_pts_cloud(path):

    data = np.loadtxt(path, skiprows=1)

    # XYZ: mm -> m
    points = data[:, :3] / 1000.0

    cloud = o3d.geometry.PointCloud()

    cloud.points = o3d.utility.Vector3dVector(points)

    # RGB
    if data.shape[1] >= 7:

        colors = data[:, 4:7] / 255.0

        cloud.colors = o3d.utility.Vector3dVector(
            np.clip(colors, 0.0, 1.0)
        )

    return cloud


# ---------------------------------------------------------
# Sphere
# ---------------------------------------------------------

def create_sphere_pcd(
    center,
    radius,
    number_of_points,
    color
):

    sphere = o3d.geometry.TriangleMesh.create_sphere(
        radius=radius,
        resolution=8
    )

    sphere.translate(center)

    pcd = sphere.sample_points_uniformly(
        number_of_points=number_of_points
    )

    pcd.paint_uniform_color(color)

    return pcd


# ---------------------------------------------------------
# Get actual finger-tip points
# ---------------------------------------------------------

def get_finger_tip_points(grasp):
    """
    Return the two fingertip contact points at the ACTUAL tip
    (forward-most point) of the gripper mesh generated by:

        grasp.to_open3d_geometry()

    GraspNet's gripper convention (plot_gripper_pro_max):
        - R[:, 0] = approach axis. The finger boxes span local x from
          -(depth_base + finger_width) [wrist side] to +depth [tip].
          grasp.translation sits at local x=0, which is `depth` BEHIND
          the visual tip — that's why the sphere looked "inner".
        - R[:, 1] = finger-opening axis (the two fingers sit at
          y = ±width/2).

    So the tip point = translation, pushed forward by `depth` along
    the approach axis, then offset by ±width/2 along the opening axis.
    """

    R = grasp.rotation_matrix          # (3, 3)
    t = grasp.translation              # (3,)
    width = grasp.width                # this grasp's actual width
    depth = grasp.depth                # this grasp's actual depth

    approach_axis = R[:, 0]            # forward/approach direction
    open_axis = R[:, 1]                # finger-opening direction

    tip_center = t + depth * approach_axis   # push out to the tip

    tip_1_world = tip_center - (width / 2.0) * open_axis
    tip_2_world = tip_center + (width / 2.0) * open_axis

    return tip_1_world, tip_2_world
# ---------------------------------------------------------
# Convert grasps -> point clouds
# ---------------------------------------------------------

def grasps_to_pointcloud(grasp_path):

    grasps = GraspGroup(
        str(grasp_path)
    ).sort_by_score()

    if MAX_GRASPS > 0:

        grasps = grasps[
            :min(MAX_GRASPS, len(grasps))
        ]

    print(
        "Number of grasps:",
        len(grasps)
    )

    all_grasp_points = []
    all_grasp_colors = []

    all_contact_points = []
    all_contact_colors = []

    # -----------------------------------------------------
    # Process every grasp
    # -----------------------------------------------------

    for grasp_index in range(len(grasps)):

        grasp = grasps[grasp_index]

        # -------------------------------------------------
        # EXACT GraspNet gripper mesh
        # -------------------------------------------------

        grasp_mesh = (
            grasp.to_open3d_geometry()
        )

        grasp_pcd = (
            grasp_mesh.sample_points_uniformly(
                number_of_points=POINTS_PER_GRASP
            )
        )

        points = np.asarray(
            grasp_pcd.points
        )

        if len(points) > 0:

            all_grasp_points.append(
                points
            )

            # Red gripper
            all_grasp_colors.append(
                np.tile(
                    np.array(
                        [[1.0, 0.0, 0.0]]
                    ),
                    (len(points), 1)
                )
            )

        # -------------------------------------------------
        # Actual fingertip locations
        # -------------------------------------------------

        tip_1, tip_2 = (
            get_finger_tip_points(grasp)
        )

        # -------------------------------------------------
        # Blue sphere at first fingertip
        # -------------------------------------------------

        sphere_1 = create_sphere_pcd(
            tip_1,
            CONTACT_SPHERE_RADIUS,
            CONTACT_SPHERE_POINTS,
            [0.0, 0.0, 1.0]
        )

        # -------------------------------------------------
        # Blue sphere at second fingertip
        # -------------------------------------------------

        sphere_2 = create_sphere_pcd(
            tip_2,
            CONTACT_SPHERE_RADIUS,
            CONTACT_SPHERE_POINTS,
            [0.0, 0.0, 1.0]
        )

        # -------------------------------------------------
        # Store sphere 1
        # -------------------------------------------------

        p1 = np.asarray(
            sphere_1.points
        )

        all_contact_points.append(
            p1
        )

        all_contact_colors.append(
            np.tile(
                np.array(
                    [[0.0, 0.0, 1.0]]
                ),
                (len(p1), 1)
            )
        )

        # -------------------------------------------------
        # Store sphere 2
        # -------------------------------------------------

        p2 = np.asarray(
            sphere_2.points
        )

        all_contact_points.append(
            p2
        )

        all_contact_colors.append(
            np.tile(
                np.array(
                    [[0.0, 0.0, 1.0]]
                ),
                (len(p2), 1)
            )
        )

    # =====================================================
    # Build gripper point cloud
    # =====================================================

    grasp_cloud = (
        o3d.geometry.PointCloud()
    )

    if len(all_grasp_points) > 0:

        all_grasp_points = (
            np.concatenate(
                all_grasp_points,
                axis=0
            )
        )

        all_grasp_colors = (
            np.concatenate(
                all_grasp_colors,
                axis=0
            )
        )

        grasp_cloud.points = (
            o3d.utility.Vector3dVector(
                all_grasp_points
            )
        )

        grasp_cloud.colors = (
            o3d.utility.Vector3dVector(
                all_grasp_colors
            )
        )

    # =====================================================
    # Build contact point cloud
    # =====================================================

    contact_cloud = (
        o3d.geometry.PointCloud()
    )

    if len(all_contact_points) > 0:

        all_contact_points = (
            np.concatenate(
                all_contact_points,
                axis=0
            )
        )

        all_contact_colors = (
            np.concatenate(
                all_contact_colors,
                axis=0
            )
        )

        contact_cloud.points = (
            o3d.utility.Vector3dVector(
                all_contact_points
            )
        )

        contact_cloud.colors = (
            o3d.utility.Vector3dVector(
                all_contact_colors
            )
        )

    return grasp_cloud, contact_cloud


# ---------------------------------------------------------
# Process one object
# ---------------------------------------------------------

def process_object(object_dir):

    object_name = object_dir.name

    pts_path = (
        object_dir / "rgb_0.pts"
    )

    grasp_path = (
        object_dir / "rgb_0.grasp.npy"
    )

    if not pts_path.exists():

        print(
            f"SKIP {object_name}: "
            "rgb_0.pts not found"
        )

        return

    if not grasp_path.exists():

        print(
            f"SKIP {object_name}: "
            "rgb_0.grasp.npy not found"
        )

        return

    # -----------------------------------------------------
    # Output directory
    # -----------------------------------------------------

    output_dir = (
        OUTPUT_ROOT / object_name
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    rgb_output = (
        output_dir / "rgb.pcd"
    )

    grasp_output = (
        output_dir / "grasp.pcd"
    )

    contact_output = (
        output_dir / "contact.pcd"
    )

    combined_output = (
        output_dir /
        "grasp_with_contacts.pcd"
    )

    print()
    print("=" * 60)
    print(
        "Processing:",
        object_name
    )
    print("=" * 60)

    # =====================================================
    # Object point cloud
    # =====================================================

    object_cloud = load_pts_cloud(
        pts_path
    )

    print(
        "Object points:",
        len(object_cloud.points)
    )

    o3d.io.write_point_cloud(
        str(rgb_output),
        object_cloud
    )

    # =====================================================
    # Gripper + fingertip spheres
    # =====================================================

    grasp_cloud, contact_cloud = (
        grasps_to_pointcloud(
            grasp_path
        )
    )

    print(
        "Gripper points:",
        len(grasp_cloud.points)
    )

    print(
        "Contact sphere points:",
        len(contact_cloud.points)
    )

    # =====================================================
    # Save gripper
    # =====================================================

    o3d.io.write_point_cloud(
        str(grasp_output),
        grasp_cloud
    )

    # =====================================================
    # Save contact spheres
    # =====================================================

    o3d.io.write_point_cloud(
        str(contact_output),
        contact_cloud
    )

    # =====================================================
    # Combined
    # =====================================================

    combined_grasp = (
        grasp_cloud + contact_cloud
    )

    o3d.io.write_point_cloud(
        str(combined_output),
        combined_grasp
    )

    print()
    print("Saved:")

    print(
        " ",
        rgb_output
    )

    print(
        " ",
        grasp_output
    )

    print(
        " ",
        contact_output
    )

    print(
        " ",
        combined_output
    )


# ---------------------------------------------------------
# Main
# ---------------------------------------------------------

def main():

    OUTPUT_ROOT.mkdir(
        parents=True,
        exist_ok=True
    )

    object_dirs = sorted(
        [
            p
            for p in INPUT_ROOT.iterdir()
            if p.is_dir()
        ]
    )

    print(
        "Input:",
        INPUT_ROOT
    )

    print(
        "Output:",
        OUTPUT_ROOT
    )

    print(
        "Objects:",
        len(object_dirs)
    )

    for object_dir in object_dirs:

        try:

            process_object(
                object_dir
            )

        except Exception as e:

            print(
                f"ERROR processing "
                f"{object_dir.name}: {e}"
            )

    print()
    print("=" * 60)
    print("DONE")
    print("=" * 60)


if __name__ == "__main__":
    main()
